"""
build_golden.py — Regenerates the golden fixture.

    WINDFALL_FIXTURES=1 python -m backend.tools.build_golden

One committed full-pipeline response per seeded traveler. It is the contract
the frontend builds against, and the regression net for the backend: a change
that alters any outcome shows up as a diff in review rather than as a surprise
on judging day.
"""
from __future__ import annotations

import json
import os

os.environ.setdefault("WINDFALL_FIXTURES", "1")

from backend.recovery import pipeline, repository  # noqa: E402

OUT = os.path.join(os.path.dirname(__file__), "..", "recovery", "seed", "golden.json")


def main():
    payload = {
        "_readme": (
            "Generated by backend/tools/build_golden.py. Do not hand-edit. "
            "One full pipeline response per seeded traveler, covering all four "
            "outcomes plus the upstream-failure path."
        ),
        "queue": repository.queue(),
        "results": {},
    }
    for row in repository.all_travelers():
        result = pipeline.run(row["traveler_id"])
        payload["results"][row["traveler_id"]] = result.to_dict()

    with open(OUT, "w", encoding="utf-8") as fh:
        json.dump(payload, fh, indent=2, ensure_ascii=False)

    seen = sorted({r["decision"]["outcome"] for r in payload["results"].values()})
    print("wrote {} results -> {}".format(len(payload["results"]), os.path.abspath(OUT)))
    print("outcomes covered:", ", ".join(seen))


if __name__ == "__main__":
    main()
