/**
 * Recovery API client.
 *
 * Same-origin by design: next.config.ts rewrites /api/recovery/* to Flask, so
 * nothing here needs a backend hostname and no API origin ends up in the
 * client bundle.
 *
 * That rewrite is also why failures need care. When Flask is not listening,
 * the failure is generated by the Next proxy rather than by the API, and it
 * arrives as a 500 carrying the plain string "Internal Server Error" -- which
 * is exactly the unhelpful message an analyst sees when they forget to start
 * the backend. But Flask returns 500 too, for a genuine pipeline crash, and
 * that response carries a JSON body naming the real cause.
 *
 * Status alone cannot tell those apart, so the body shape decides: if the
 * response explains itself, that explanation wins; if it does not, the request
 * never reached the API and we say so.
 */
import type { QueueResponse, RecoveryResult, SendReceipt } from "./types";

/**
 * Console chrome is analyst-facing, so it stays English. Indonesian is for
 * traveler-facing copy -- the email and WhatsApp previews.
 */
const UNREACHABLE =
  "Cannot reach the recovery backend. Start Flask (or run docker compose up), then try again.";

async function request<T>(input: RequestInfo | URL, init?: RequestInit): Promise<T> {
  let res: Response;
  try {
    res = await fetch(input, init);
  } catch (err) {
    // An abort is the caller cancelling on purpose -- picking a second cart,
    // or leaving the screen. Callers suppress it by checking `name`, so it has
    // to keep its name rather than be flattened into a connection error.
    if (err instanceof DOMException && err.name === "AbortError") throw err;
    throw new Error(UNREACHABLE);
  }

  if (res.ok) return (await res.json()) as T;

  // Did the API speak for itself? A 404 for an unknown traveler, a 409 with
  // nothing to send, a 503 naming the three ways to configure inference -- all
  // carry { error } and all say more than any message invented here.
  let detail: string | null = null;
  try {
    const body = (await res.json()) as { error?: string };
    if (body?.error) detail = body.error;
  } catch {
    /* not JSON: nothing to quote */
  }
  if (detail) throw new Error(detail);

  // No structured error. On the statuses a broken proxy hop produces, the
  // request never reached Flask, whatever the status number suggests.
  if (res.status === 500 || res.status === 502 || res.status === 503 || res.status === 504) {
    throw new Error(UNREACHABLE);
  }
  throw new Error(res.statusText || "Request failed");
}

export async function fetchQueue(signal?: AbortSignal): Promise<QueueResponse> {
  return request<QueueResponse>("/api/recovery/queue", { signal });
}

export async function runRecovery(
  travelerId: string,
  signal?: AbortSignal,
): Promise<RecoveryResult> {
  return request<RecoveryResult>("/api/recovery/run", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ travelerId }),
    signal,
  });
}

/**
 * Deliver the approved notification.
 *
 * Deliberately a separate call from runRecovery. Reading a trace must never
 * send anything; delivery needs its own explicit click.
 */
export async function approveAndSend(
  travelerId: string,
  signal?: AbortSignal,
): Promise<SendReceipt> {
  return request<SendReceipt>("/api/recovery/send", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ travelerId }),
    signal,
  });
}
